# -*- coding: utf-8 -*-
"""addTheFirstTwoDigitByUserEnter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l-eHuhfATLCyArcYFmnUY8fF99wqJQGS
"""

#Create The Variable And The Data Enter The User
num1 =  input("Enter The Number Any   :" )

#Create The Variable And The Sicling Are Apply
num1_sicling = num1[0]

#Print The Sicling Data
print(num1_sicling)

#Create The Variable And The Sicling Are Apply
num2_sicling = num1[1]

#Print The Sicling Data
print(num2_sicling )

#Create The Variable And It's Store Data of Data Cast
num1_tpye_casting = int(num1_sicling)

#Create The Variable And It's Store Data of Data Cast
num2_tpye_casting = int(num2_sicling)

#Create The Variable And It's Addition Of Two Variable
add_Two_Number = num1_tpye_casting + num2_tpye_casting

#Print The Addition Of The Result
print("The Of Addition Of Two Variable's : ",add_Two_Number)

