# -*- coding: utf-8 -*-
"""automatePizzaCalculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MkPzX8x3iZ1S3Nr4vQW8nn2ouz1gU3y1
"""

#Print The Some Statement
print("welcome to Python Pizza Deliveries")
#Create The Variable it's Store The Size in Small , Medium and Large
size = input("What Size pizza do you want? S, M, or L : ")
#Create The Variable it's Store The add_pepperoni in Yes Or No
add_pepperoni = input("Do You want pepperoni? Y or N :")
#Create The Variable it's Store The extra_cheese  in Yes Or No
extra_cheese = input("Do You want Extra Cheese? Y or N :")

#Use The If Condition it's Size is Equal to Size Small
if size == "S":
#Addition The Bill of 15 Dollar
  bill = 15
#Use The ELIf Condition it's Size is Equal to Size Medium
elif size == "M":
#Addition The Bill of 20 Dollar
  bill = 20
#Use The ELIf Condition it's Size is Equal to Size Large
elif size == "L":
#Addition The Bill of 25 Dollar
  bill = 25
#Use The If Condition it's Add_pepperoni is Equal to add_pepperoni is Yes
if add_pepperoni == "Y":
#Use The If Condition it's Size is Equal to Small
  if size == "S":
#Addition The Bill of 2 Dollar
    bill +=  2
  else:
#Addition The Bill of 3 Dollar
      bill += 3
#Use The If Condition it's extra_cheese is Equal to Y
if extra_cheese =="Y":
#Addition The Bill of 1 Dollar
  bill += 1
#Use The Else Condition it's extra_cheese is Equal to   Yes
else:
   bill
print(f"Your's Final Bill is : {bill}")