# -*- coding: utf-8 -*-
"""bmiCalculatorItsCheckWeightCondition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15B80V9LvvRiiIgL1xIhrikD_d0yEt9tq
"""

#Create The Variable And The Data Enter The User in Weight Variable
weight = float(input("Enter The weight in kilogram : "))
#Create The Variable And The Data Enter The User in Height  Variable
height = float(input("Enter The Height in  Meter's : "))

#Create The Variable And The Calculate Bmi In Store the Bmi Variable
bmi = ((weight) / (height ** 2))
#Create The Variable And The Round Bmi In Store the bmi_r Variable
bmi_r = round(bmi,2)

#It's Check the the if Condition The Bmi is less than 18.5
if bmi < 18.5 :
  print(f"Your's Bmi is {bmi_r} And Your's are under weight")
#It's Check the the elif Condition The Bmi is less than 25
elif bmi < 25:
  print(f"Your's Bmi is {bmi_r} And Your's are under weight normal weight")
#It's Check the the elif Condition The Bmi is less than 30
elif bmi < 30:
  print(f"Your's Bmi is {bmi_r} And Your's are over weight")
#It's Check the the if Condition The Bmi is less than 35
elif bmi < 35:
  print(f"Your's Bmi is {bmi_r} And Your's are obese")
#It's Check the the if Condition The Bmi is greater than 35
elif bmi > 35:
  print(f"Your's Bmi is {bmi_r} And Your's are clinically obese")