# -*- coding: utf-8 -*-
"""calculateRemainingDaysWeeksAndMonths.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xe6NzC_JykGYe_mlgs4hVlvd63pibPfU
"""

#Create The Variable And Input The Age By User It's Store The Variable
age = input("What is your Current Age?")
#Create The Variable , Calculate The Remaining Years And It's Type Casting Of Age Variable
remaining_years = 90 - float(age)
#Create The Variable , Calculate The Remaining Days
remaining_days = remaining_years * 365
#Create The Variable , Calculate The Remaining Weeks
remaining_weeks = remaining_years * 52
#Create The Variable , Calculate The Remaining Months
remaining_months = remaining_years * 12
#Print The  Remaining Years , Remaining Weeks and Remaining Months
print(f"You have {remaining_days} days, {remaining_weeks} weeks ,and {remaining_months} months left. ")