# -*- coding: utf-8 -*-
"""calculateBmi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YGAQf-OfCgw0gfdrDvXbyvDCk47WsgC_
"""

#Create The Variable And Input The Age By User It's Store The Variable
height = input("enter your height in m:")
#Create The Variable And Input The Age By User It's Store The Variable
weight = input("enter your weight in kg:")
#Create The Variable , Calculate The BMI , Type Casting And Apply The Square Of Height
bmi = float(weight) / (float(height) ** 2)
#Create The Variable And it's Round The BMI In Only two Digit's
round_bmi = round(bmi,2)
#Print The Your's BMI
print("Your's Bmi Is : ",round_bmi)