# -*- coding: utf-8 -*-
"""checkLeapYear.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cB0jzIPNbSjl-5l_w6OXtJ79a4zgdx_J
"""

#Create The Variable And The Data Enter The User in Year Variable
year = int(input("Enter the Variable :"))

#It's Check the the if Condition The year is apply modules by 4 And it's value is Equal to 0 than it's Leap Year Else Not Leap Year
if year % 4 == 0 :
#It's Check the the if Condition The year is apply modules by 100 And it's value is Equal to 0 than it's Not Leap Year Else Leap Year
  if year % 100  == 0 :
#It's Check the the if Condition The year is apply modules by 400 And it's value is Equal to 0 than it's Leap Year Else Not Leap Year
    if year % 400 == 0:
      print("Leap Year")
    else:
      print("Not Leap Year")
  else:
    print("Leap Year")
else:
  print("Not Leap Year")