# -*- coding: utf-8 -*-
"""checkTheTypeOfData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O0TD7FU82Iwp_cAXlZcYsFzlzyo-mm5w
"""

#Create The Variable And Save The Length Of The String Length
input_string = len((input("What is Your's Name : ")))

#Print The Data Type
print("The Type Of Data is",type(input_string))

#Print The Data Type
print(type(len((input("What is Your's Name : ")))))