# -*- coding: utf-8 -*-
"""concateTwoString.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VHhRbl3kFFH3hxiY_rvDmABi7MojxVSR
"""

#Concate Two String
print('123'+'654')

#Concate Two String
print('Ahmad ' + 'Ali')