# -*- coding: utf-8 -*-
"""dataInInteger.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tz60lC5MWiYLixjY8Wla6BrAriAZqvb5
"""

#Data Type
#Integer
#Add The Two Number
print(236+789)