# -*- coding: utf-8 -*-
"""dataTypeInString.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LgqDdfjTmleq3VktcJ5yGzHEOLl_EFKl
"""

#Data Type
#String
#Print The Subscripting of The String
print('Sufyan'[0])

#Print The Subscripting of The String
print('Sufyan'[1])

#Print The Subscripting of The String
print('Sufyan'[-1])

#Print The Subscripting of The String
print('Sufyan'[2])

#Print The Subscripting of The String
print('Sufyan'[3])

#Print The Subscripting of The String
print('Sufyan'[4])