# -*- coding: utf-8 -*-
"""dataTypeInBoolean.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ZhN-vmDHt6QXK6hnUPNaUPpOJo7MBE9
"""

#Data Type
#Boolean
#Assign The Variable
a = True
b = False

#Print The Data Of Variable A
print(a)

#Print The Data Of Variable B
print(b)