# -*- coding: utf-8 -*-
"""dataTypeInFloat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18cI8jvZpIIWb_S_udahRgXQ7n_F-qdOZ
"""

#Data Type
#Float
#Add The Two Number
print(566.223+7893.23)