# -*- coding: utf-8 -*-
"""largeNumberInPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hVCenJr0QlGOz_kgVc8qTKQ6ajz8gv3u
"""

#Large Number Use In Python
num = 789455_7899_778
num1 = 799244_44522_7789

#Add The Two Number
addNum = num +num1
#Print The Result Variable Data
print('The Addition of Two Number : ',addNum)