# -*- coding: utf-8 -*-
"""lengthOfString.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uhOa-F-7kXCD3lBFubktyUdMqR-zXTvI
"""

#Print The Length of the String
print(len('Sufyan Ahmad'))