# -*- coding: utf-8 -*-
"""lengthOfStringByUserInput.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B2iXthIEFS6025HBuE2AhM7NIDES1sBO
"""

#Create The Variable And Save The Length Of The String Length
input_string = len((input("What is Your's Name : ")))

#Print The Variable Data
print("Your name has " , input_string , "Character's.")