# -*- coding: utf-8 -*-
"""numberIsOddOrEven.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nTQjaq2F_ID0_ZrhrZzmxaplrF-bkzie
"""

#Create The Variable it's Store The Any Number As Your Choose
number = int(input("Which Number do you Want Choose "))
#Use The If Condition it's Apply The Modules And Comparsion Operation Check The Even Or Odd
if number % 2 == 0:
  print("This is Even Number")
#Use The If Condition it's  Show The Odd Number
else:
  print("This is Odd Number")