# -*- coding: utf-8 -*-
"""rideOrNotRideRollerCoaster.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S5VfjOZDmnwQGDSoigpsNJApPxBgqgJq
"""

#Print The Some Statement
print("Welcome To The rollercoaster")
#Create The Variable it's Store The Height in integer in cm
height = int(input("What is Your Height in cm? "))
#Use The If Condition it's Greater Than 120 Cm's Then Can Ride
if height > 120:
  print("You Can ride the  rollercoaster ")
#Use The Else Condition it's  Equal And Less Than 120 Cm's Then Cannot Ride
else:
  print("Sorry  You have to grow taller before you can ride")