# -*- coding: utf-8 -*-
"""rollerCoasterCalculateBill.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FKZtG9_rDamJY8iCn73I4bcD_8UYZaBW
"""

#Print The Some Statement
print("Welcome To The rollercoaster")
#Create The Variable it's Store The Height in integer in cm
height = int(input("What is Your Height in cm? "))
#Create The Variable it's Store The Age  in integer
age =  int(input("Enter the age : "))
#Use The If Condition it's Greater Than 120 Cm's Then Can Ride
if height > 120:
  print("You Can ride the  rollercoaster ")
#Use The If Condition it's Greater Than 12 then bill is 5 dollar
  if age < 12:
    bill = 5
#Use The Elif Condition it's Greater equal Than 18 then bill is 7 dollar
  elif age <= 18:
    bill = 7
#Use The Else Condition it's Above Than 18 then bill is 12 dollar
  else:
    bill = 12
#Create The Variable it's Store The photo want click not click
  photo = input("Do You want To Photo taken? Y or N :")
#Use The If Condition it's photo equal to y then add the bill 3 dollar
  if photo == "y":
    bill = bill +3
#Use The Else Condition it's No addition in the Bill
  else:
    bill = bill
  print(bill)
#Use The Else Condition it's  Equal And Less Than 120 Cm's Then Cannot Ride
else:
  print("Sorry  You have to grow taller before you can ride")