# -*- coding: utf-8 -*-
"""typeCastingIntegerIntoFloat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mHku5jwyVSpG-a3eBF-8jPSdtGzQME0g
"""

#Create The Variable And The Data
num = 123654

#Create The New Variable And Type Casting
num_float =  float(num)

#Check The Data Type
print("The Data Type is : " ,type(num_float))