# -*- coding: utf-8 -*-
"""typeCastingIntegerIntoString.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xFJPBOV5B7hGRkLR2oietAOTvCYBu3fN
"""

#Create The Variable And The Data
num = 123654

#Create The New Variable And Type Casting
num_str = str(num)

#Check The Data Type
print("The Data Type is : " ,type(num_str))