# -*- coding: utf-8 -*-
"""typeCastingIntegerIntoString.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f3mkzSEodpBvP1v9doo_bVwbdJGfE9dB
"""

#Create The Variable And The Data
num = 123

#Create The Variable And The Data
num1 = 654

#Create The New Variable And Type Casting
num_string =  str(num)
num1_string = str(num1)

#Print The Two Varaible
print(num_string + num1_string)