# -*- coding: utf-8 -*-
"""typeCastingIntoString.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iBpAQnd2t22TPRljydRb3sQXailGo4bK
"""

#Create The Variable And Save The Length Of The String Length
input_string = len((input("What is Your's Name : ")))

#Create The New Variable And Type Casting
input_string_casting = str(input_string)

#Print The Variable Data
print("Your name has " + input_string_casting + " Character's.")